### ISSUE TITLE
Unknown variable

### ISSUE THREAD

**Issue by BabuKumaranNalini** [anantgupta129/Solar-Power-Generation-Forecasting#2]
Could you please explain what is data in corr = data.corr() in line 234 in solarpower_generation_forecasting_ann.py?

**Comment by anantgupta129** [comment]
data.corr() computes the correlation matrix in a data frame check out https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.corr.html for reference

**Comment by BabuKumaranNalini** [comment]
No, actually you do not have a variable named "data". If you run your code it is throwing an error at line 234 as the "data" variable is missing since you have not assinged it. I think it should have been "results.corr()" but then it is not showing the same heatmap plot as shown in your Github.

**Comment by anantgupta129** [comment]
It's actually the original dataset it should be `dts.corr()` I might have renamed the variable and plotted it without noticing. I will update the code

**Comment by BabuKumaranNalini** [comment]
Thanks for helping. dts.corr() it is.
