### ISSUE TITLE
How to run it 

### ISSUE THREAD

**Issue by SahithShetty** [anantgupta129/Solar-Power-Generation-Forecasting#3]
Hey Mr. Anant. This is Sahith.  I came accross this project while searching for some forecasting projects and I really liked this. 
I ask for a small help from your side. I just request you to tell me how could I run this code in brief.
Hope you will reply me :)

Thanks!!

**Comment by anantgupta129** [comment]
Hi @SahithShetty 
The notebook has step by step process to run this repo. You can follow it. 
Since this is not an issue am closing it. If you need any further assistance, contact me over LinkedIn or mail can be found over my profile
